### ISSUE TITLE
Question about the files after training

### ISSUE THREAD

**Issue by deadlykitten4** [LWL-cpu/SCPRG-master#5]
Hi, thanks for your excellent work. When I finished training and want to evaluate it. I encountered a problem is that in the corresponding output directory, there are only **validation_predictions_span.jsonlines** and **test_predictions_span.jsonlines**, but don't have **validation_golden_head.jsonlines**, **validation_predictions_head.jsonlines**, **test_golden_head.jsonlines** and **test_predictions_head.jsonlines**, which means I can't run the evaluation successfully, could you please help me tackle with this issue? Thanks a lot!

**Comment by LWL-cpu** [comment]
You need to run the evaluate rams/wiki.sh script, which will automatically generate validation_golden_head.jsonlines, validation_predictions_head.jsonlines, test_golden_head.jsonlines, and test_predictions_head.jsonlines.  Remember to change the OUTPUT_DIR in the script.

**Comment by deadlykitten4** [comment]
Thanks a lot! I found the reason is that I didn't install the spacy correctly.
